/*
 * AUTOGENERATED tcarstens January 2014
 */
#include "tests.h"


#if TEST_SET & TEST_320
#define mpz_set_ul  mpz_set_ocl_ul320

#define ul_bitsize  (320)
#define ul          ocl_ul320


#define ul_test_all        ul320_test_all
#define ul_test_setup      ul320_test_setup
#define ul_test_clear      ul320_test_clear
#define ul_test_run_kernel ul320_test_run_kernel

#define ul_rand_seed_two   "kern_ul320_rand_seed_two"
#define ul_rand_seed_three "kern_ul320_rand_seed_three"

#define ul_binop_test      ul320_binop_test
#define ul_add_test        "kern_ul320_add_test"
#define ul_sub_test        "kern_ul320_sub_test"
#define ul_mul_test        "kern_ul320_mul_test"

#define ul_divremop_test   ul320_divremop_test
#define ul_divrem_test     "kern_ul320_divrem_test"

#define ul_compare_test    ul320_compare_test
#define ul_cmp_test        "kern_ul320_cmp_test"
#define ul_cmp_ui_test     "kern_ul320_cmp_ui_test"

#define ul_mod_binop_test  mod320_binop_test
#define ul_mod_add_test    "kern_mod320_add_test"
#define ul_mod_sub_test    "kern_mod320_sub_test"
#define ul_mod_mul_test    "kern_mod320_mul_test"
#define ul_mod_mul_test2   "kern_mod320_mul_test2"
#define ul_mod_inv_test    "kern_mod320_inv_test"



#define ul_pm1pp1_reorder      "kern_ul320_pm1pp1_reorder"

#define ul_pm1op_test      ul320_pm1op_test
#define ul_pm1_stage1      "kern_ul320_pm1_stage1"
#define ul_pm1_stage2      "kern_ul320_pm1_stage2"

#define ul_pp1op_test      ul320_pp1op_test
#define ul_pp1_stage1      "kern_ul320_pp1_stage1"
#define ul_pp1_stage2      "kern_ul320_pp1_stage2"

#define ul_ecmop_test      ul320_ecmop_test
#define ul_ecm_reorder     "kern_ul320_ecm_reorder"
#define ul_ecm_stage1      "kern_ul320_ecm_stage1"
#define ul_ecm_stage2      "kern_ul320_ecm_stage2"


#include "test_all.h"
#endif /* TEST_320 */
