/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (224)


#define ul_ocl             ocl_ul224
#define ul_init_ocl        ocl_ul224_init
#define ul_clear_ocl       ocl_ul224_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul224
#define mpz_get_ul_ocl     mpz_get_ocl_ul224


#define ecm_process_ocl    ecm_ul224_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul224_reorder"


#define ellM_point_t       ellM224_point_t
#define mod                mod224
#define ul                 ul224
#define ul_init            ul224_init
#define ul_clear           ul224_clear
#define ul_set_ui          ul224_set_ui
#define ul_cmp_ui          ul224_cmp_ui
#define ul_cmp             ul224_cmp
#define mod_init           mod224_init
#define mod_clear          mod224_clear
#define mod_set            mod224_set
#define mpz_get_ul         mpz_get_ul224
#define mpz_set_ul         mpz_set_ul224


#include "ocl_process_common.h"
