/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (96)


#define ul_ocl             ocl_ul96
#define ul_init_ocl        ocl_ul96_init
#define ul_clear_ocl       ocl_ul96_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul96
#define mpz_get_ul_ocl     mpz_get_ocl_ul96


#define ecm_process_ocl    ecm_ul96_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul96_reorder"


#define ellM_point_t       ellM96_point_t
#define mod                mod96
#define ul                 ul96
#define ul_init            ul96_init
#define ul_clear           ul96_clear
#define ul_set_ui          ul96_set_ui
#define ul_cmp_ui          ul96_cmp_ui
#define ul_cmp             ul96_cmp
#define mod_init           mod96_init
#define mod_clear          mod96_clear
#define mod_set            mod96_set
#define mpz_get_ul         mpz_get_ul96
#define mpz_set_ul         mpz_set_ul96


#include "ocl_process_common.h"
