/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (128)


#define ul_ocl             ocl_ul128
#define ul_init_ocl        ocl_ul128_init
#define ul_clear_ocl       ocl_ul128_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul128
#define mpz_get_ul_ocl     mpz_get_ocl_ul128


#define ecm_process_ocl    ecm_ul128_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul128_reorder"


#define ellM_point_t       ellM128_point_t
#define mod                mod128
#define ul                 ul128
#define ul_init            ul128_init
#define ul_clear           ul128_clear
#define ul_set_ui          ul128_set_ui
#define ul_cmp_ui          ul128_cmp_ui
#define ul_cmp             ul128_cmp
#define mod_init           mod128_init
#define mod_clear          mod128_clear
#define mod_set            mod128_set
#define mpz_get_ul         mpz_get_ul128
#define mpz_set_ul         mpz_set_ul128


#include "ocl_process_common.h"
