/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (288)


#define ul_ocl             ocl_ul288
#define ul_init_ocl        ocl_ul288_init
#define ul_clear_ocl       ocl_ul288_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul288
#define mpz_get_ul_ocl     mpz_get_ocl_ul288


#define ecm_process_ocl    ecm_ul288_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul288_reorder"


#define ellM_point_t       ellM288_point_t
#define mod                mod288
#define ul                 ul288
#define ul_init            ul288_init
#define ul_clear           ul288_clear
#define ul_set_ui          ul288_set_ui
#define ul_cmp_ui          ul288_cmp_ui
#define ul_cmp             ul288_cmp
#define mod_init           mod288_init
#define mod_clear          mod288_clear
#define mod_set            mod288_set
#define mpz_get_ul         mpz_get_ul288
#define mpz_set_ul         mpz_set_ul288


#include "ocl_process_common.h"
