/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (320)


#define ul_ocl             ocl_ul320
#define ul_init_ocl        ocl_ul320_init
#define ul_clear_ocl       ocl_ul320_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul320
#define mpz_get_ul_ocl     mpz_get_ocl_ul320


#define pm1_process_ocl    pm1_ul320_process_ocl
#define kern_pm1_stage1    "kern_pm1_ul320_stage1"
#define kern_pm1_reorder   "kern_pm1_ul320_reorder"
#define kern_pm1_stage2    "kern_pm1_ul320_stage2"

#define pp1_process_ocl    pp1_ul320_process_ocl
#define kern_pp1_stage1    "kern_pp1_ul320_stage1"
#define kern_pp1_reorder   "kern_pp1_ul320_reorder"
#define kern_pp1_stage2    "kern_pp1_ul320_stage2"

#define ecm_process_ocl    ecm_ul320_process_ocl
#define kern_ecm_stage1    "kern_ecm_ul320_stage1"
#define kern_ecm_reorder   "kern_ecm_ul320_reorder"
#define kern_ecm_stage2    "kern_ecm_ul320_stage2"


#define ellM_point_t       ellM320_point_t
#define mod                mod320
#define ul                 ul320
#define ul_init            ul320_init
#define ul_clear           ul320_clear
#define ul_set_ui          ul320_set_ui
#define ul_cmp_ui          ul320_cmp_ui
#define ul_cmp             ul320_cmp
#define mod_init           mod320_init
#define mod_clear          mod320_clear
#define mod_set            mod320_set
#define mpz_get_ul         mpz_get_ul320
#define mpz_set_ul         mpz_set_ul320
#define pm1_stage1_ul      pm1_stage1_ul320
#define pm1_stage2_ul      pm1_stage2_ul320
#define pp1_stage1_ul      pp1_stage1_ul320
#define pp1_stage2_ul      pp1_stage2_ul320
#define ecm_stage1_ul      ecm_stage1_ul320
#define ecm_stage2_ul      ecm_stage2_ul320


#include "ocl_process_common.h"
