/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (160)


#define ul_ocl             ocl_ul160
#define ul_init_ocl        ocl_ul160_init
#define ul_clear_ocl       ocl_ul160_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul160
#define mpz_get_ul_ocl     mpz_get_ocl_ul160


#define ecm_process_ocl    ecm_ul160_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul160_reorder"


#define ellM_point_t       ellM160_point_t
#define mod                mod160
#define ul                 ul160
#define ul_init            ul160_init
#define ul_clear           ul160_clear
#define ul_set_ui          ul160_set_ui
#define ul_cmp_ui          ul160_cmp_ui
#define ul_cmp             ul160_cmp
#define mod_init           mod160_init
#define mod_clear          mod160_clear
#define mod_set            mod160_set
#define mpz_get_ul         mpz_get_ul160
#define mpz_set_ul         mpz_set_ul160


#include "ocl_process_common.h"
