/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (64)


#define ul_ocl             ocl_ul64
#define ul_init_ocl        ocl_ul64_init
#define ul_clear_ocl       ocl_ul64_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul64
#define mpz_get_ul_ocl     mpz_get_ocl_ul64


#define ecm_process_ocl    ecm_ul64_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul64_reorder"


#define ellM_point_t       ellM64_point_t
#define mod                mod64
#define ul                 ul64
#define ul_init            ul64_init
#define ul_clear           ul64_clear
#define ul_set_ui          ul64_set_ui
#define ul_cmp_ui          ul64_cmp_ui
#define ul_cmp             ul64_cmp
#define mod_init           mod64_init
#define mod_clear          mod64_clear
#define mod_set            mod64_set
#define mpz_get_ul         mpz_get_ul64
#define mpz_set_ul         mpz_set_ul64


#include "ocl_process_common.h"
