/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (320)


#define ul_ocl             ocl_ul320
#define ul_init_ocl        ocl_ul320_init
#define ul_clear_ocl       ocl_ul320_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul320
#define mpz_get_ul_ocl     mpz_get_ocl_ul320


#define ecm_process_ocl    ecm_ul320_process_ocl
#define kern_ecm_reorder   "kern_ecm_ul320_reorder"


#define ellM_point_t       ellM320_point_t
#define mod                mod320
#define ul                 ul320
#define ul_init            ul320_init
#define ul_clear           ul320_clear
#define ul_set_ui          ul320_set_ui
#define ul_cmp_ui          ul320_cmp_ui
#define ul_cmp             ul320_cmp
#define mod_init           mod320_init
#define mod_clear          mod320_clear
#define mod_set            mod320_set
#define mpz_get_ul         mpz_get_ul320
#define mpz_set_ul         mpz_set_ul320


#include "ocl_process_common.h"
